#!/bin/bash
version="1.5.0";
cpSetup_banner() {
	echo -n "${GREEN}"
	cat <<"EOT"
  _________.__                   __          
 /   _____/|  |__   ____   _____/  |______   
 \_____  \ |  |  \ /  _ \ /  _ \   __\__  \  
 /        \|   Y  (  <_> |  <_> )  |  / __ \_
/_______  /|___|  /\____/ \____/|__| (____  /
        \/      \/                        \/ 
EOT
echo -e "${BLUE}                       Version ${version}${YELLOW}"
	cat <<"EOT"
   ____                               __            _             
  / __ \ _ __ ___   __ _ _ __   ___  / _| ___  _ __(_) ___  _ __  
 / / _` | '_ ` _ \ / _` | '_ \ / _ \| |_ / _ \| '__| |/ _ \| '_ \ 
| | (_| | | | | | | (_| | | | | (_) |  _| (_) | |  | | (_) | | | |
 \ \__,_|_| |_| |_|\__,_|_| |_|\___/|_|  \___/|_|  |_|\___/|_| |_|
  \____/                                                          
EOT
echo -n "${NORMAL}"
}
#                     Shoota cpanel Script
# ------------------------------------------------------------------------------
# @usage ./shoota [(-h|--help)] [(-v|--verbose)] [(-V|--version)] [(-u|--unattended)]
# ------------------------------------------------------------------------------
# @copyright Copyright (C) 2019 itfinden spa
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
# ------------------------------------------------------------------------------

# Uncomment out the code below to make the script break on error
# set -e
#
# Functions and Definitions
#
# Define help function

source ./app/shoota_help.inc


# Declare vars. Flags initalizing to 0.
verbose="--quiet";
yumargs="";
unattended=0;
builddir=~/cpsetupbuild/
sshport=222;
rootemail="your@email.com";
functions=0;
cloudflare_api_key="YOUR_CLOUDFLARE_API_KEY_HERE";
cloudflare_company_name="YOUR CLOUDFLARE HOSTING COMPANY NAME HERE";
railgun_token="YOUR_TOKEN_HERE";
railgun_host="YOUR_PUBLIC_IP_OR_HOSTNAME";

# Debugging on OSX (due to getopt issues), so i define brew location for getopt in env variable
if [[ -z "${SMYLES_GETOPT}" ]]; then
	# ENV variable not set, so use default getopt
	GETOPT_CMD="getopt"
else
	GETOPT_CMD="${SMYLES_GETOPT}"
fi

# Execute getopt
ARGS=$("$GETOPT_CMD" -o "hvVur:R" -l "help,verbose,version,unattended,run:,functions" -n "cpsetup" -- "$@");

#Bad arguments
if [ $? -ne 0 ];
then
    help;
fi
eval set -- "$ARGS";

while true; do
    case "$1" in
        -h|--help)
            shift;
            help;
            ;;
        -v|--verbose)
            shift;
                    verbose="";
            ;;
        -V|--version)
            shift;
                    echo "$version";
                    exit 1;
            ;;
        -u|--unattended)
            shift;
                    unattended="1";
                    yumargs="-y";
            ;;
        -r|--run)
            shift;
                    if [ -n "$1" ];
                    then
                        runcalled="1";
                        run="$1";
                        shift;
                    fi
            ;;
        -R|--functions)
            shift;
            	functions=1;
            ;;

        --)
            shift;
            break;
            ;;
    esac
done

BLACK=$(tput setaf 0)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
LIME_YELLOW=$(tput setaf 190)
POWDER_BLUE=$(tput setaf 153)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
WHITE=$(tput setaf 7)
BRIGHT=$(tput bold)
NORMAL=$(tput sgr0)
BLINK=$(tput blink)
REVERSE=$(tput smso)
UNDERLINE=$(tput smul)

BLACKBG=$(tput setab 0)
REDBG=$(tput setab 1)
GREENBG=$(tput setab 2)
YELLOWBG=$(tput setab 3)
BLUEBG=$(tput setab 4)
MAGENTABG=$(tput setab 5)
CYANBG=$(tput setab 6)
WHITEBG=$(tput setab 7)

source ./app/shoota_func.inc

cpanel_installed=$(/usr/local/cpanel/cpanel -V 2>/dev/null)

clear
cpSetup_banner
echo -e "\n";
if (($functions > 0 )); then
	echo -e "${RED}Here's a list of available functions to call when using the -r or --run command:${NORMAL}"
	echo -e "\n";
	compgen -A function | egrep -vw 'givemeayes|help|headerBlock|lineBreak|stepcheck|promptForSSHPort|promptForRootForwardEmail|cpSetup_banner';
	echo -e "\n";
	exit;
fi

if [ -z "$cpanel_installed" ]; then
	echo -e "${WHITEBG}${RED}${BRIGHT}${BLINK}Whoa Nelly!${NORMAL}${WHITEBG}${BLACK}It looks like cPanel is not installed on this server!${NORMAL}"
	if givemeayes "${RED}¿Le gustaría instalar cPanel antes de ejecutar este script??${NORMAL}"; then
		headerBlock "No hay problema, primero instalemos cPanel ... esto podría tardar un minuto ... o dos ... o treinta ... por favor, espere ..."
		echo -e "\n";
		read -p "Presione la tecla [Enter] cuando esté listo ..."
		cd /home && curl -o latest -L http://httpupdate.cpanel.net/latest && sh latest
	else
		if ! givemeayes "${RED}De acuerdo, no hay problema, ¿desea continuar con este script (sin instalar cPanel)??${NORMAL}"; then
			echo -e "\n${RED}Script eliminado, nada ha sido cambiado o instalado.\n${NORMAL}"
			exit;
		fi
	fi
fi

echo -e "${WHITEBG}${RED}${BRIGHT}${BLINK}Aviso!${NORMAL}${WHITEBG}${BLACK} Un par de cosas que debes saber sobre este script:${NORMAL}"
echo -e "* Debes Tener habilitado ${YELLOW}ioncube${NORMAL} en ${YELLOW}WHM${NORMAL} ${BLUE}Tweak Settings${NORMAL} > ${MAGENTA}cPanel PHP Loader${NORMAL} para instalar Softaculous (opcional)"
echo -e "* Debes pasar por la configuración inicial en ${YELLOW}WHM${NORMAL}, seleccionando el tipo de servidor dns y ftp (cuando inicias sesión por primera vez en WHM) antes de ejecutar este script."
echo -e "${BLUE}Te gusto este Script?  trabajemos por un cpanel mas seguro en https://github.com/itfinden/shoota ... !${NORMAL}"
echo -e "\n";

if (($unattended > 0)); then
	echo -e "${YELLOW}!!! WARNING: Unattended mode ENABLED, MAKE SURE YOU SET ALL CONFIG VALUES IN THIS SCRIPT !! YOU HAVE BEEN WARNED !!${NORMAL}"
fi

if [ $run ]; then
	echo -e "${YELLOW}RUN command specified, only the${RED} $run ${YELLOW}function will be executed. ${NORMAL}"
fi

echo -e "\n";

if ! givemeayes "${RED}Empezamos con la Instalacion?${NORMAL}"; then
	echo -e "\n${RED}Script eliminado, nada ha sido cambiado o instalado.\n${NORMAL}"
	exit;
fi

if [ -d "$builddir" ]; then
	rm -rf $builddir
fi

mkdir $builddir

if [ $run ]; then
	${run}
	exit;
fi

if stepcheck "yum colors"; then
	headerBlock "Adding yum colors if does not exist..."
	installYumColors
fi

if stepcheck "Actualizar el server entero"; then
	headerBlock "Actualizando los Paquetes por favor espere..."
	yum clean all ${verbose}
	yum update ${yumargs} ${verbose}
fi

if stepcheck "install ConfigServer MailManage"; then
	headerBlock "Installing ConfigServer MailManage, please wait..."
	installMailManage
fi

if stepcheck "install ConfigServer MailQueue"; then
	headerBlock "Installing ConfigServer MailQueue, please wait..."
	installMailQueue
fi

if stepcheck "install ConfigServer Firewall"; then
	headerBlock "Installing ConfigServer Firewall, please wait..."
	installFirewall
fi

if stepcheck "install ConfigServer ModSecurity Control (WHM already has this builtin)"; then
	headerBlock "Installing ConfigServer ModSecurity Control, please wait..."
	installModSecurityControl
fi

if stepcheck "install ConfigServer Explorer"; then
	headerBlock "Installing ConfigServer Explorer, please wait..."
	installExplorer
fi

if stepcheck "install R-fx Malware Detect"; then
	headerBlock "Installing R-fx Malware Detect, please wait..."
	installMalDetect
fi

if stepcheck "install ConfigServer Exploit Scanner (requires license)"; then
	headerBlock "Installing ConfigServer Exploit Scanner, please wait..."
	installCXS
fi

echo -e "\n";
echo -n "${YELLOW}!! HEADS UP !!${RED}( You SHOULD do this NOW ): ${NORMAL}You must have ${YELLOW}ioncube${NORMAL} enabled in ${YELLOW}WHM${NORMAL} under ${BLUE}Tweak Settings${NORMAL} > ${MAGENTA}cPanel PHP Loader${NORMAL} or Softaculous will not install"
echo -e "\n";
if stepcheck "install Softaculous"; then
	headerBlock "Installing Softaculous, please wait..."
	installSoftaculous
fi

if stepcheck "install Account DNS Check"; then
	headerBlock "Installing Account DNS Check, please wait..."
	installAccountDNSCheck
fi

if stepcheck "install WatchMySQL"; then
	headerBlock "Installing WatchMySQL, please wait..."
	installWatchMySQL
fi

if stepcheck "install MySQL Tuner"; then
	headerBlock "Installing MySQL Tuner, please wait..."
	installMySQLTuner
fi

if stepcheck "harden server configuration"; then
	hardenServerConfig
fi

if stepcheck "install ClamAV from source"; then
	headerBlock "Installing ClamAV from source, please wait..."
	installClamAV
fi

if stepcheck "install CloudFlare mod_cloudflare"; then
	promptForCloudFlareConfig
	headerBlock "Downloading and installing mod_cloudflare, please wait..."
	installModCloudFlare
fi

if stepcheck "add CloudFlare IPv4 and IPv6 subnets to ConfigServer Firewall allow list"; then
	headerBlock "Adding IPv4 subnets to CSF allow list, please wait..."
	addCloudFlareIPv4SubnetsToCSF
	headerBlock "Adding IPv6 subnets to CSF allow list, please wait..."
	addCloudFlareIPv4SubnetsToCSF
	headerBlock "Restarting ConfigServer Firewall, please wait..."
	csf -r
fi

if stepcheck "install CloudFlare RailGun (includes memcached)"; then
	installCloudFlareRailGun
fi

if stepcheck "configure memcached for RailGun using sockets"; then
	configureMemCachedRailGunSockets
fi

if stepcheck "configure CloudFlare RailGun"; then
	configureCloudFlareRailGun
fi

if stepcheck "install AfterLogic WebMail Lite"; then
	installAfterLogicWebmailLite
fi

if stepcheck "install Lets Encrypt for AutoSSL"; then
	installLetsEncryptAutoSSL
fi

headerBlock "Cleaning up build files, please wait..."
cd ~
rm -rf $builddir
echo -e "\n${CYAN}Script Complete! Profit!\n${NORMAL}"
echo -e "\n${WHITEBG}${RED}!!! If you installed mod_cloudflare DONT FORGET to login to WHM and recompile Apache with mod_cloudflare (using EasyApache) !!! \n${NORMAL}"
